# Generated by Django 6.0.2 on 2026-02-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.CharField(blank=True, help_text='Path to image in Next.js public folder (e.g., /blog_images/blog1.jpg)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, help_text='Path to image in Next.js public folder (e.g., /project_images/project1.jpg)', max_length=500, null=True),
        ),
    ]
